name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use the latest version of the checkout action

    - name: Decode SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > discordbot.pem
        chmod 600 discordbot.pem

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.4  # Using a specific version for better stability
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ runner.temp }}/discordbot.pem
        script: |
          /home/ubuntu/update_bot.sh
  
